language: node_js
node_js:
  - "0.10"
matrix:
  include:
    - node_js: "0.10"
      env: UNDERSCORE=1.4.4 BACKBONE=1.0
    - node_js: "0.10"
      env: UNDERSCORE=1.5 BACKBONE=1.0
    - node_js: "0.10"
      env: UNDERSCORE=1.6 BACKBONE=1.0
    - node_js: "0.10"
      env: UNDERSCORE=1.4.4 BACKBONE=1.1.0
    - node_js: "0.10"
      env: UNDERSCORE=1.5 BACKBONE=1.1
before_install:
  - npm config set ca ""
install:
  - npm install -g grunt-cli
  - npm install
  # Which matrix settings -- otherwise default
  - "[ $BACKBONE ] && npm install backbone@$BACKBONE"
  - "[ $UNDERSCORE ] && npm install underscore@$UNDERSCORE"
after_success:
  - npm run-script coverage
